# Generated by Django 4.2.8 on 2024-01-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="activity",),
        migrations.RemoveField(model_name="profile", name="age",),
        migrations.RemoveField(model_name="profile", name="goal",),
        migrations.RemoveField(model_name="profile", name="height",),
        migrations.RemoveField(model_name="profile", name="sex",),
        migrations.RemoveField(model_name="profile", name="weight",),
    ]
