# Generated by Django 4.2.8 on 2024-01-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_allergy_profile_diet_alter_profile_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="calories", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile", name="carbs", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile", name="fat", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile", name="protein", field=models.IntegerField(default=0),
        ),
    ]
